### ISSUE TITLE
No results after search

### ISSUE THREAD

**Issue by pyros-cyber** [andros21/ytdl-mpv#1]
After searching for something, the result page is empty. 
While debugging I found out that the problem is in `_cacheTable()`, 
in the `.import --csv <filename> <tablename>` [statements](https://github.com/andros21/ytdl-mpv/blob/112a71741102bc64b4d19507ee01be3529ba6389/bin/ytdl-mpv#L207-L213). 

OS: Linux Mint 20.1
Sqlite3 Version: `3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1`

**Comment by andros21** [comment]
Oh yes my bad ... only from [3.32.0](https://www.sqlite.org/releaselog/3_32_0.html) `--csv` flag was added
